### ISSUE TITLE
Design refresh: Event detail page

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#1267]
AC
- [ ] Looks like design
- [ ] HTML valid

**Comment by stevejalim** [comment]
@malqinneh @valgrimm Before I pick this up, it would be good to know if we are going to continue to show all the details that an event page can show (full address, etc) or if they are being dropped (they're not in the mocks in Abstract). 

eg [here](https://developer-portal.dev.mdn.mozit.cloud/events/perfmatters-conference-2020/) we have an event with venue details.

It's also currenlty possible (in data terms, even if we don't leverage it much in production) to show:
* speakers at the event
* topics associated with the event

I can freestyle support for the following, but if there's resource to get the mockup extended, that'd be great:

* venue details (text)
* venue location (map)
* speakers at the event
* topics associated with the event

**Comment by malqinneh** [comment]
Thank you Steve! Spoke with Val, here are some decisions from that conversation:

- We need to add a secondary button next to [Register] that takes users to the official website of the event page. Button should be labeled as [Official Website]
- We need the ability to add another button that takes you to a specific URL labeled as [Event Content]
- Val agrees to leave out the address due to complications (venue changing, etc.)
