### ISSUE TITLE
Design refresh: Remove external link indicator

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#1270]

**Comment by malqinneh** [comment]
I would just zap it. @valgrimm any strong feelings?

**Comment by valgrimm** [comment]
I concur. Zap it (: 
It was an explicit requirement in the pile of one zillion requirement docs we encountered back when we were rolling out the site originally, which is why we have kept it so long, but like many of those requirements it was intended for a magazine site, not the site we have now. I'm happy to make a case for eliminating it if anyone raises an issue.

**Comment by stevejalim** [comment]
⚡️
