### ISSUE TITLE
Run Lighthouse on new design

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1358]
...to get an idea of frontend performance bottlenecks

**Comment by stevejalim** [comment]
This could be done after deployment to production as part of tuning it up, rather than this delaying a  release of the redesign, I think

**Comment by valgrimm** [comment]
I concur.

**Comment by stevejalim** [comment]
Initial speedcurve results are looking positive, given we don't want the portal to be a PWA anyway.

![Screenshot 2020-05-27 at 12.25.02.png](https://images.zenhubusercontent.com/5d7b94dd167772000187fd33/38ea2686-0628-45f9-8018-5066d2e0945d)

Overall performance is 30% faster than pre-redesign, too, which is a pleasant surprise

**Comment by stevejalim** [comment]
However there are still viable things we can do, given time:

* Serve static assets with an efficient cache policy -- we can talk to @limed about this for the S3-hosted assets
* Properly size images -- we could tweak the image-rendition generation so that Wagtail produces images that are exactly the size the CSS resizes them to. 
* Preconnect to required origins -- I thought we were doing this, but maybe we lost it during the redesign...?
* Eliminate render-blocking resources -- worth a look

**Comment by valgrimm** [comment]
Sounds great!
