### ISSUE TITLE
Add event section to topic pages

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1392]
AC
- [ ] Section should be identical in design and capacity to "What 're developing"/"What we're working on" 
- [ ]  Should appear above "What 're developing"/"What we're working on" and below the main card content

**Comment by stevejalim** [comment]
@valgrimm If the new Events unit is above the "What we're working on" unit, and we keep the design the same, the grey background will connect them to each other, which is not ideal.

Could we put it below "What we're working on" and give it a white background, so that if both appear then it'll not suffer that shared-background problem? (If we have the event section above "what we're working on", but with a white background, the event section might bleed into the featured items area

**Comment by valgrimm** [comment]
> Could we put it below "What we're working on" and give it a white background, so that if both appear then it'll not suffer that shared-background problem? 

yup.
