### ISSUE TITLE
Admin side: External content sortable by date updated

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1400]
AC: Add column "Updated" as in Events and Posts areas

**Comment by valgrimm** [comment]
Like this
![image.png](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/cd141d42-f3ae-4ea4-ae70-431ee71240e5)

Not as it is
![image.png](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/77652ac3-e4ec-4e4b-812f-812768a647d9)

**Comment by stevejalim** [comment]
@valgrimm Thanks for the screenie.

Because the way we do external content is a bit non-standard in Wagtail terms, it might take a bit of wrangling to get the ordering etc, in place. (At least, based on a distant memory of showing the Published State column, I suspect it'll be non-trivial compard to most Wagtail Admin configuration.)

Very happy to try, but wanted to check if simply changing the ordering so that newer results are at the top by default (without the sorting, but still newest -> oldest instead of oldest -> newest) would solve the actual user pain. Doing _that_ will be very quick.

**Comment by valgrimm** [comment]
> Very happy to try, but wanted to check if simply changing the ordering so that newer results are at the top by default (without the sorting, but still newest -> oldest instead of oldest -> newest) would solve the actual user pain. Doing that will be very quick.

Yup, that would make a big difference (:

**Comment by stevejalim** [comment]
OK - let's aim for the simplest thing for now. Putting a tiny estimate on it
