### ISSUE TITLE
Add redirect support to static build

### ISSUE THREAD

**Issue by dcgauld** [mdn/developer-portal#264]
Currently, statically building the site and uploading to S3 doesn't honor redirects from Wagtail. wagtail/wagtail-bakery#14 seems to cover adding support for this, but hasn't had much movement recently (although a custom solution has been suggested [here](https://github.com/wagtail/wagtail-bakery/issues/14#issuecomment-299202214)).

It might be that the static build isn't around long enough for this to be worth doing.

https://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html

**Comment by stevejalim** [comment]
Happy to take this on

**Comment by stevejalim** [comment]
While we may not be using redirects yet, having them working and in our back pocket is definitely wortwhile. Thanks for raising @dcgauld!

**Comment by stevejalim** [comment]
It looks like django-bakery already supports this via `BuildableRedirectView`: https://github.com/datadesk/django-bakery/blob/a2f1f74b03951450d797ec70cc9872d6c694e1e3/bakery/views/base.py#L166

So it might be worth exploring how to leverage this, rather than write our own. 

Even better if we can find a way to work it into wagtail-bakery
