### ISSUE TITLE
Add support for S3 media uploads

### ISSUE THREAD

**Issue by dcgauld** [mdn/developer-portal#265]
Currently, all media uploaded from within Wagtail is uploaded locally and shared between instances via an [EFS volume](https://aws.amazon.com/efs/). We should probably enable S3 media uploads within Wagtail, potentially via something like the django-storages [S3 backend](https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html)?

https://wagtail.io/blog/amazon-s3-for-media-files/

cc @stevejalim @limed

**Comment by stevejalim** [comment]
Yeah, definitely.

**Comment by limed** [comment]
Yes please for this 👍

**Comment by stevejalim** [comment]
I'll pick this up soon

**Comment by stevejalim** [comment]
So, had a look into this, then remembered that django-bakery takes care of this when you call its `build` step. 

> By default, this wipes the build directory if it exists, then builds any static files in the STATIC_ROOT to the STATIC_URL, any media files in the MEDIA_ROOT to the MEDIA_URL and all pages generated by the buildable views listed in BAKERY_VIEWS.

[source](https://django-bakery.readthedocs.io/en/latest/managementcommands.html#build)

As such, we don't need to store user-uploaded media in S3 in order to make it more efficiently/safely available. We _could_ do it, though.

Pros (of uploading user media to S3):

* it _would_ reduce the risk of disk space exhaustion within the `app` container's volume.

Cons:

* each uploaded file will add to the time it takes to build the static site, because the file will need to be downloaded from S3 (in order to upload it to a different S3 bucket, effectively)

So, is this worth it? @limed - what was your key reason for wanting media in S3, please?

**Comment by limed** [comment]
> 
> Pros (of uploading user media to S3):
> 
> * it _would_ reduce the risk of disk space exhaustion within the `app` container's volume.
> 
> 
> Cons:
> 
>  * each uploaded file will add to the time it takes to build the static site, because the file will need to be downloaded from S3 (in order to upload it to a different S3 bucket, effectively)
> 
> 
> So, is this worth it? @limed - what was your key reason for wanting media in S3, please?

You make a good point here in that build will take a longer time, main reason why I would want `S3` to host uploaded media is because I would like to get away from using something like `EFS` which is what is currently hosting the media.

That being said I realize that the only people that will be affected by this switch are content creator, the folks who consume the site in a readonly fashion will not care about it. I do however feel that S3 might be a little bit more resilient in terms of storing data which protects us from data loss, plus you get to version your objects. I am open to a bigger discussion about this though and can be swayed either way.

**Comment by stevejalim** [comment]
@limed Yeah, I agree about resilience. I'll try it out.

I was thinking the user media should live in a separate bucket from the static site - again for resilience. Agreed?

**Comment by stevejalim** [comment]
Nearly there.... but then I just hit
```
~/Code/developer-portal/media/images $ docker-compose exec app python manage.py build
INFO:bakery.management.commands.build:Build started
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/fs/osfs.py", line 337, in makedir
    os.mkdir(sys_path, mode)
FileNotFoundError: [Errno 2] No such file or directory: b'/app/build/https:/REDACTED.s3.amazonaws.com'
```

**Comment by limed** [comment]
> I was thinking the user media should live in a separate bucket from the static site - again for resilience. Agreed?
Agreed on this
