### ISSUE TITLE
Make featured cards smaller so that more content can appear above the fold on topics pages

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#834]
This is a request from Kathy Giori (WebThings) 22 November

![featuredcardsizing.PNG](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/1272b738-e513-4c01-b8b6-0271169d5ce8)

**Comment by stevejalim** [comment]
I think there's going to be debate about this one and where 'the fold' is these days. However, the Featured area can handle up four things being featured, and if this is set up then it's in a "one then three" layout, and I think the row of three is going to be shorter/shallower than a row of two, because things are scaled proportionally. (Does that make any sense? Hope so!)

**Comment by valgrimm** [comment]
Would it be possible to have two items at the top and the big wide item at the bottom @stevejalim ?

**Comment by stevejalim** [comment]
With code changes yes, including some additional flag in the admin to say
way to say which layout you want.

However, two small followed by one big does give me an information
hierarchy eye-twitch :o)

**Comment by valgrimm** [comment]
I agree on the inof hierarchy eye twitch, but I also see what Kathy said. Only solution I can think of is a tall side card running vertically across rows rather than a wide card running horizontally across columns. However, that is neither practical from a technical standpoint nor part of the original design. Im not sure how best to solve this, or if just to let it drop.

**Comment by valgrimm** [comment]
No longer needed
